import {
  MarvinOctavdio,
  MayoFalmonti,
  MochFahri,
  MuhammadRamzi,
  RinaldiRaymond,
  RizaBuditomo,
} from "../../people/assets/export-assets";

export const dataKeyPeople = [
  {
    id: 1,
    name: "Riza Buditomo",
    title: "Managing Partner",
    photo: RizaBuditomo,
    description:
      "Riza Buditomo has more than 20 years of experience and has multiple legal talents. Not only he is the Partner leading the trade and tax (including export / import) practices, but he is also advising clients in corporate commercial and M&A matters on regular basis. Before establishing Anagata, Riza was a Partner at one of the most prestigious international law firms in Jakarta. <br /><br />Riza is amongst a very few lawyers who has an educational background of accounting and tax as well as law. Riza's work includes, cross border trade issues, export/import, customs, supply chain, tobacco industry, food industry, manufacturing/logistic & transportation, anti-dumping, free trade agreements, land acquisition/property/real estate, and other international corporate commercial work including high profile mergers and acquisitions & business transfers. He has extensive experience in dealing with government authorities such as the Ministry of Trade, the Customs Office and the Indonesian Investment Coordinating Board (Badan Koordinasi Penanaman Modal– BKPM).<br /><br /> Riza is a highly experienced and well-trained Tax Court litigator and is admitted in the Tax Court of Indonesia (both for Customs and Tax). Riza handles customs & excise related matters and Customs litigation cases on regular basis. Riza also advises on tax regulatory issues. <br /><br /> One of Riza’s achievement is his appointment as the Head of the Permanent Committee on ASEAN Economic Community and International Matters by the Indonesian Chambers of Commerce & Industry (Kamar Dagang dan Industri Indonesia or KADIN) until 2021. Recently, he is included in the A List of 100 Top Lawyers and an elite list of 50 Future Legal Leader by Asia Business Law Journal.",
    award: true,
    linkedin: "Riza Buditomo",
    phoneNumber: "+628159110720",
    education: [
      "University of Indonesia Diploma Accounting (2002)",
      "University of Indonesia B.A. Law",
      "University of California, UC Davis",
    ],
    email: "riza.buditomo@anagatalaw.com",
    keyPractices: [
      "Tax",
      "International Trade",
      "Trade Remedies Customs/excise",
      "Export/Import",
      "Supply chain & FTA",
      "Merger & Acquisitions",
      "Corporate/commercials",
      "Retail and Commerce (including e-commerce)",
      "Industrial",
      "Manufacturing and transportation (including logistics)",
    ],
  },
  {
    id: 2,
    name: "Muhammad Ramzi",
    title: "Partner",
    photo: MuhammadRamzi,
    description:
      "With almost a decade of experience under his belt, Muhammad Ramzi possesses several legal skills and is adept at providing counsel to clients in corporate, commercial, and trade-related issues. Prior to joining Anagata as Partner, Ramzi was an associate at a highly esteemed international law firm located in Jakarta. He is known for his meticulous attention to detail, strong negotiation skills, and ability to navigate complex legal landscapes.<br/><br/>Ramzi specializes in international corporate commercial work, with expertise in cross-border trade issues, export/import, supply chain, FMCG, Technology, Media & Telecommunication (TMT), Personal Data Protection (PDP), manufacturing, direct selling, automotive, FTA, and high-profile mergers and acquisitions. <br/><br/>With his vast experience, he has successfully navigated dealings with prominent government authorities, including the Ministry of Trade, the Ministry of Industry, and the Indonesian Investment Coordinating Board (Badan Koordinasi Penanaman Modal – BKPM).<br/><br/>Ramzi possesses extensive experience in the Indonesian conglomerate sector and is widely recognized for his proficiency in managing real estate-related commercial transactions. Additionally, he has a strong passion for sports, which he has further cultivated through his work in sports law. He has represented numerous professional sports organizations in contract negotiations and has offered expert guidance on sponsorship, endorsement, and licensing agreements.",
    award: false,
    linkedin: "Muhammad Ramzi",
    phoneNumber: "+628563212629",
    education: ["University of Airlangga B.A. Law"],
    email: "muhammad.ramzi@anagatalaw.com",
    keyPractices: [
      "International Trade",
      "Supply Chain & FTA, Merger & Acquisitions",
      "Corporate/commercials",
      "Retail and Commerce (including e-commerce and direct selling)",
      "TMT",
      "PDP",
      "Manufacturing",
      "Real Estate",
      "Sport",
      "Automotive",
    ],
  },
  {
    id: 3,
    name: "Marvin Octavdio",
    title: "Partner",
    photo: MarvinOctavdio,
    description:
      "Marvin Octavdio is a distinguished tax law expert with extensive experience spanning international and domestic legal landscapes. A graduate of the Faculty of Law at the University of Indonesia, Marvin furthered his specialization by earning a Master of Laws (LL.M.) in International Taxation from New York University, becoming the first Indonesian admitted to this prestigious program.<br/><br/>His career includes experiences in Tax Practice Group at a highly-regarded international law firm in Jakarta and the largest domestic law firm in Indonesia, where he honed his expertise in complex cross-border tax issues. Additionally, his tenure at a Big 4 accounting firm in the United States equipped him with a unique blend of legal and financial acumen, enabling him to provide strategic solutions for corporations navigating domestic and global tax challenges.<br/><br/>With various experiences in tax advisory services and tax dispute resolution, Marvin offers clients innovative and practical tax strategies that align with business goals and regulatory frameworks. His multidisciplinary experience sets him apart as a lawyer in shaping and resolving critical tax issues for his clients.",
    award: false,
    linkedin: "Marvin Octavdio",
    phoneNumber: "+6281332738300",
    education: [
      "University of Indonesia, Bachelor of Law",
      "New York University - Master of Laws (LL.M) in International Taxation",
    ],
    email: "marvin.octavdio@anagatalaw.com",
    keyPractices: [
      "Tax Advisory",
      "Tax Litigation",
      "International Tax",
      "Indirect Tax",
      "Tax Incentives",
      "Cross-Border Transaction",
    ],
  },
  {
    id: 4,
    name: "Mochamad Fachri",
    title: "Of Counsel",
    photo: MochFahri,
    description:
      "Mochamad Fachri has more than 23 years of experience advising clients on litigious and advisory aspects of competition law. On the advisory side, he has been advising clients on applying this law in all aspects of a company's operations, particularly concerning the distribution of products, contacts with competitors, and joint venture issues. On the litigious side, he has litigated landmark competition law cases from the initial stage, investigation at the Competition Commission (KPPU) up to final appeal at the Supreme Court. <br/><br/>He also advises on more than one hundred merger transactions filed through the KPPU's merger review process. These include transactions that have been subject to challenge from KPPU.<br/><br/>Mochamad Fachri has more than 25 years of experience in advising a wide range of companies, both multinationals and nationals, on all aspects of Indonesian corporate laws for private (non-listed) companies, including establishment of companies,  market entry issues, corporate governance issues.<br/><br/>Clients include leading multinationals and Indonesian companies in manufacturing, e-commerce, information technology, pharmaceutical sectors.<br/><br/>He was twice ranked as an elite competition law practitioner in Indonesia by Global Competition Review for 2017 and 2023; this publication's highest ranking.",
    award: false,
    linkedin: "Mochamad Fachri",
    phoneNumber: "+628159101030",
    education: [
      "University of Padjadjaran B.A. Law",
      "Colombia University Master of Laws- LLM",
    ],
    email: "mochamad.fachri@anagatalaw.com",
    keyPractices: [
      "Company law",
      "Foreign Investment",
      "Market Entry",
      "Competition Law",
      "Consumer Protection",
    ],
  },
  // {
  //   id: 5,
  //   name: "Mayo Falmonti",
  //   title: "Of Counsel",
  //   photo: MayoFalmonti,
  //   description:
  //     "Mayo Folmanti has nearly a decade of experience in Intellectual Property Rights Law. He has advised Intellectual Property Rights issues on various transactions of major multinational companies. His career path started from a state Owned company and move into law in the music-related business and after that he started helping company locally and internationally in IPR related.<br/><br/>He has extensive experience in Trademark contentious matters serving a clients in various industries: startup,, Automotive, Hotel, F&B even game industry . From registration, rebuttal, objection matters mostly in trademark.<br/><br/>He is a recognized  Intellectual Property Rights consultant, duly admitted to the Ministry of law and human rights also member of the AKHKI. In the intricate realm of customs and international trade, Rinaldi Raymond stands as a stalwart, ready to guide and safeguard business interests with a wealth of experience and legal acumen.",
  //   award: false,
  //   linkedin: "Mayo Folmanti",
  //   phoneNumber: "+628158710770",
  //   education: [
  //     "University of Indonesia, Indonesia B Law in Economic Law",
  //     "University of Indonesia, Indonesia Master of Law with specialty of Corporate Law",
  //   ],
  //   email: "mayo.falmonti@anagatalaw.com",
  //   keyPractices: ["Trademark", "Industrial design", "Copyright", "Licensing"],
  // },
  {
    id: 6,
    name: "Rinaldi Raymond",
    title: "Attorney Director | Head of Customs Practice",
    photo: RinaldiRaymond,
    description:
      "Rinaldi Raymond has nearly a decade of experience in customs and international trade-related projects. He has advised import, export & customs issues on various cross-border transactions of major multinational companies. His illustrious career path saw him in the ranks of a prestigious international law firm headquartered in Jakarta as a mid-associate and, before that, occupying a role as an assistant manager at a prominent Big 4 consulting firm.<br/><br/>He has extensive experience in serving a broad range of multinational clients in various industries: Mining, Oil & Gas, Energy, Automotive, Manufacturing, FMCG, Healthcare, Textile, and Electronics. By meticulously navigating the regulatory labyrinth, he ensures customs compliance. He addresses various regulatory and commercial concerns, thus mitigating the specter of penalties and the daunting prospect of resource-intensive audits. Rinaldi's credentials are beyond reproach.<br/><br/>He is a recognized customs expert, duly admitted to the Ministry of Finance, and a distinguished member of the esteemed Institute of Indonesia Chartered Accountants. Moreover, he is a seasoned litigator in the hallowed halls of the Tax Court of Indonesia, wielding specialized expertise as a registered Customs attorney. In the intricate realm of customs and international trade, Rinaldi Raymond stands as a stalwart, ready to guide and safeguard business interests with a wealth of experience and legal acumen.",
    award: false,
    linkedin: "Rinaldi Raymond",
    phoneNumber: "+6281808749666",
    education: [
      "Ernst Abbe Hochschule Jena University of Applied Sciences, Germany. MBA",
      "South Westphalia University of Applied Sciences, Germany. B.A",
      "Swiss German University, Indonesia. S.E",
    ],
    email: "rinaldi.raymond@anagatalaw.com",
    keyPractices: [
      "International Trade & Supply Chain",
      "Customs Valuation",
      "Customs Audit",
      "Customs Disputes (Objection, Appeal, Judicial Review)",
      "Customs Diagnostics Review (Internal Audit)",
      "Customs Due Diligence",
      "HS Code Tariff Classification and Free Trade Agreements",
    ],
  },
];
